### ISSUE TITLE
Fix Response of register

### ISSUE THREAD

**Issue by remixxx31** [Pixilib/GaelO_Flow_Backend#39]
- [ ] Maybe repair of nodeMailer
- [ ] Response is 500 for api

**Comment by salimkanoun** [comment]
@remixxx31 

dans le register le confirmation token n'est pas écrit en base de données, il est généré apres la création du user, comment se fait la validation du token pour le change password ? 

`    const newUser = await this.usersService.create({
      Email: registerDto.Email,
      Firstname: registerDto.Firstname,
      Lastname: registerDto.Lastname,
      Username: registerDto.Username,
      SuperAdmin: false,
      RoleName: 'User',
      Password: null,
    });
    const confirmationToken =
      await this.authService.createConfirmationToken(newUser);`

**Comment by remixxx31** [comment]
En fait createCOnfirmationToken fait plusieurs choses , peut -être trop?
Elle créer le token, la date d'expiration et elle update le USer par la même occasion
J'ai utilisé les fonctions dans password.ts.
En fait dans register cette fonction :
sendChangePasswordEmail -> va créer une url qui lorqu'on clique dessus appelle l'API change-password dans le mail!
Je sais pas si ça réponds à la question ?
