### ISSUE TITLE
Rassembler les guards dans un repertoire src/guards

### ISSUE THREAD

**Issue by salimkanoun** [Pixilib/GaelO_Flow_Backend#43]
On a des guards eclaté dans role, dans authorization,

Mieux vaut rassembler les guards dans un meme repertoire, ca simplifira la compréhension du projet et ca a l'air d'etre une bonne pratique en Nest

"We now will create a folder named guards under src folder" https://medium.com/@shkim04/implement-guards-in-nestjs-8c654173bbe9

**Comment by AntoninLaudon** [comment]
https://github.com/Pixilib/GaelO_Flow_Backend/commit/bdd3a2bedff0a4e6e849321e40df9c1d624c4889
