### ISSUE TITLE
mettre definitions des enums dans le repertoire constants

### ISSUE THREAD

**Issue by salimkanoun** [Pixilib/GaelO_Flow_Backend#45]
y a l'air d'avoir le repertoire constants qui est la de base pour définir toute les contants, y mettre nos enums (QueryAnswerType, TagPoliciesn ProcessingMaskEnum, ProcessingMaskEnum)

Les harmoniser je suis pas sur qu'il faille les faire finir par enum, regarder dans nest comment sont nommées leurs enums

**Comment by salimkanoun** [comment]
dans leur exemple les enums ne contiennement pas "Enum" dans leurs noms

https://docs.nestjs.com/openapi/types-and-parameters#enums

**Comment by AntoninLaudon** [comment]
https://github.com/Pixilib/GaelO_Flow_Backend/commit/9114b4be98c6a67787d3a05bce58cd6d544e4abe
