### ISSUE TITLE
contolleur option

### ISSUE THREAD

**Issue by salimkanoun** [Pixilib/GaelO_Flow_Backend#82]
`  async getOptions(): Promise<Option> {
    const options = await this.optionService.getOptions();
    delete options.Id;`

Pourquoi ne pas maquer le id comme on fait avec le password plutot que de le delete à la main ?

**Comment by AntoninLaudon** [comment]
j'ai essayé et il semble que @Exclude() ne marche pas ici, donc je retire Id à la main

**Comment by salimkanoun** [comment]
Hum c'est pas possible pourquoi ça marcherait pour le password de user et pas pour enlever l'Id ?

**Comment by AntoninLaudon** [comment]
Je pense que c'est parce que on rajoute des choses dans l'objet que on retourne (les variables d'environnement) et que du coup ce n'est plus le type entity 'Option'

**Comment by salimkanoun** [comment]
OK alors fait un DTO OptionResponse ou tu mettra les propriété de Options de la db et les variables qui viennent des env (et ou tu mets pas l'ID)
