### ISSUE TITLE
Role controller

### ISSUE THREAD

**Issue by salimkanoun** [Pixilib/GaelO_Flow_Backend#84]
`  async findAll(@Query() withLabels: WithLabels): Promise<Role[]> {
    const allRoles = await this.roleService.findAll();
    if (withLabels.WithLabels) {
      const allRoleLabels = await this.roleService.getAllRoleLabels();
      allRoles.forEach((role) => {
        role['labels'] = allRoleLabels
          .filter((roleLabel) => roleLabel.Role.Name === role.Name)
          .map((roleLabel) => roleLabel.Label.Name);
      });
    }

    return allRoles;
  }`

C'est pas fou comme factorisation, si tu a la propriété withLabel le mieux est d'avoir dans le roleService une méthode "findAllWithLabel" qui integrera la jointure directement
ou alors dans findAll ajouter un boolean withLabel pour avoir ou non la jointure 

Ca permet de faire une seule requette sql au lieu de 2 et de ne pas avoir à refill la jointure dans ton controlleur

**Comment by AntoninLaudon** [comment]
Je le ferais après le merge de #58 pour éviter les conflicts
