### ISSUE TITLE
Role controlleur create

### ISSUE THREAD

**Issue by salimkanoun** [Pixilib/GaelO_Flow_Backend#85]
`  async update(
    @Param('name') name: string,
    @Body() roleDto: RoleDto,
  ): Promise<void> {
    const role = await this.roleService.findOneByOrFail(name);

    const requiredKeys = [
      'import',
      'anonymize',
      'export',
      'query',
      'autoQuery',
      'delete',
      'admin',
      'modify',
      'cdBurner',
      'autoRouting',
    ];`

A faire via un DTO + validator plutot

**Comment by AntoninLaudon** [comment]
duplicate https://github.com/Pixilib/GaelO_Flow_Backend/issues/58
