### ISSUE TITLE
getOauthConfig

### ISSUE THREAD

**Issue by salimkanoun** [Pixilib/GaelO_Flow_Backend#86]
`  async getOauthConfig() {
    const oauthConfig = await this.oauthConfigService.getOauthConfig();
    const oauthConfigDto = {};
    for (const config of oauthConfig) {
      oauthConfigDto[config.Provider] = {
        AuthorizationUrl: config.AuthorizationUrl,
        ClientId: config.ClientId,
      };
    }

    return oauthConfigDto;
  }`

Pas sur qu'on ait besoin d'indexer les auth config par provider, on peut simplement rendre un array d'object avec Provider, AuthorizationUrl, ClientId

**Comment by salimkanoun** [comment]
surtout que si tu a deux provider identique (deux serveur keycloack), le dernier va override le 1er et t'en aura qu'un qui apparaitra

**Comment by AntoninLaudon** [comment]
Pour l'instant on peut pas avoir 2 provider identiques. Aussi DELETE prend un provider en param, non pas un Id:

DELETE `/api/oauth-config/{provider}`

**Comment by AntoninLaudon** [comment]
Mais si tu préfères que OauthConfig se gère avec des Id plutot que des Provider c'est possible
Bien sur le fait que un provider doive être unique n'empeche pas de pouvoir retourner une liste de `{Provider: '', AuthorizationUrl: '', ClientId: ''}` plutot que un objet `{<PROVIDER>: {AuthorizationUrl: '', ClientId: ''}`

**Comment by salimkanoun** [comment]
Le provider du coup il sert a typer le serveur Oauth non ? On va avoir une gestion du token differente suivant qu'on est chez google, keycloack ou autre si les api ne sont pas tout a fait standard.

Du coup pour avoir 2 serveur Oauth du meme type, il faudrait ajouter un attribut name qui est unique en base de donnée (car l'id en soit est pas tres parlant)

et oui rester en array d'object et ajouter l'atribut name
